# Generated by Django 4.1.6 on 2023-04-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
    ]
